# Generated by Django 3.2.13 on 2022-10-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
