# Generated by Django 3.2.13 on 2022-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_admin', '0002_auto_20221020_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('is_expire', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'is_token',
            },
        ),
    ]
