# Generated by Django 3.2.13 on 2022-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_admin', '0003_token_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_store',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
