# Generated by Django 3.2.13 on 2022-11-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_admin', '0005_remove_token_store_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token_store',
            name='is_expire',
        ),
    ]
