# Generated by Django 3.2.13 on 2022-10-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_details',
            table='customer_detail',
        ),
    ]
