# Generated by Django 3.2.11 on 2023-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_partners', '0004_alter_country_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersrefstatsums',
            name='platform',
            field=models.TextField(db_column='platform', default=''),
        ),
    ]
