# Generated by Django 3.2.13 on 2022-12-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercountry',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerscountry', to='g_partners.partner'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnersplatform', to='g_partners.partner'),
        ),
    ]
