# Generated by Django 3.2.13 on 2022-12-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_partners', '0002_auto_20221202_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercountry',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='g_partners.partner'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='g_partners.partner'),
        ),
    ]
