# Generated by Django 3.2.13 on 2022-11-10 05:42

from django.db import migrations, models
import django.utils.timezone
import django_q.models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrmQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True)),
                ('payload', models.TextField()),
                ('lock', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Queued task',
                'verbose_name_plural': 'Queued tasks',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('func', models.TextField(blank=True, null=True)),
                ('hook', models.TextField(blank=True, null=True)),
                ('args', models.TextField(blank=True, help_text="e.g. 1, 2, 'John'", null=True)),
                ('kwargs', models.TextField(blank=True, help_text="e.g. x=1, y=2, name='John'", null=True)),
                ('schedule_type', models.CharField(choices=[('O', 'Once'), ('I', 'Minutes'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly'), ('C', 'Cron')], default='O', max_length=1, verbose_name='Schedule Type')),
                ('minutes', models.PositiveSmallIntegerField(blank=True, help_text='Number of minutes for the Minutes type', null=True)),
                ('repeats', models.IntegerField(default=-1, help_text='n = n times, -1 = forever', verbose_name='Repeats')),
                ('next_run', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Next Run')),
                ('cron', models.CharField(blank=True, help_text='Cron expression', max_length=100, null=True, validators=[django_q.models.validate_cron])),
                ('task', models.TextField(blank=True, null=True)),
                ('cluster', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scheduled task',
                'verbose_name_plural': 'Scheduled tasks',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('func', models.TextField(default='not recognize')),
                ('hook', models.TextField(blank=True, null=True)),
                ('args', picklefield.fields.PickledObjectField(editable=False, null=True, protocol=-1)),
                ('kwargs', picklefield.fields.PickledObjectField(editable=False, null=True, protocol=-1)),
                ('result', picklefield.fields.PickledObjectField(editable=False, null=True, protocol=-1)),
                ('group', models.TextField(blank=True, null=True)),
                ('started', models.DateTimeField(editable=False)),
                ('stopped', models.DateTimeField(editable=False)),
                ('success', models.BooleanField(default=True, editable=False)),
                ('attempt_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-stopped'],
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
            ],
            options={
                'verbose_name': 'Failed task',
                'verbose_name_plural': 'Failed tasks',
                'ordering': ['-stopped'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_q.task',),
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
            ],
            options={
                'verbose_name': 'Successful task',
                'verbose_name_plural': 'Successful tasks',
                'ordering': ['-stopped'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_q.task',),
        ),
    ]
